[package]
name = "speed_executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wr_syscalls = { path = "../wr_syscalls" }
core_affinity = "0.8.0"